# Generated by Django 4.0.6 on 2022-08-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apteka',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Аптека',
                'verbose_name_plural': 'Аптеки',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apteka_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('equipment_type', models.CharField(max_length=200)),
                ('equipment_model', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('purchase_org', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apteka_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('service_name', models.CharField(max_length=200)),
                ('service_ip', models.CharField(max_length=200)),
                ('service_login', models.CharField(blank=True, max_length=200, null=True)),
                ('service_pass', models.CharField(blank=True, max_length=200, null=True)),
                ('service_info', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Схема локальной сети',
                'verbose_name_plural': 'Схема локальной сети',
            },
        ),
    ]
